- name: 混淆 BPB worker js
  run: |
    javascript-obfuscator origin.js --output _worker.js \
    --compact true \
    --identifier-names-generator hexadecimal \
    --rename-globals true \
    --string-array true \
    --string-array-encoding 'base64' \
    --string-array-threshold 0.75 \
    --transform-object-keys true \
    --self-defending false \
    --simplify true
  continue-on-error: true # 即使命令失败也继续工作流

- name: 发送错误通知（如果混淆失败）
  if: failure()
  run: echo "混淆 BPB worker js 失败！" # 或者使用其他通知方式
